image: python:alpine

stages:
  - test
  - build

"Unit Tests":
  stage: test
  script:
    - python setup.py install
    - python -m unittest

"Build Dist":
  stage: build
  only:
    - development
    - master
  script:
    - pip install setuptools wheel
    - python setup.py sdist bdist_wheel
